// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	ID         int32
	Name       string
	TypeID     int32
	UserID     pgtype.Int4
	Attributes []byte
}

type DeviceType struct {
	ID   int32
	Name string
}

type User struct {
	ID   int32
	Name string
}
